version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker  
  
  node-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
  
  react-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client       
      - run:
          command: npm test
          working_directory: ./client
          
  docker-publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "karol22322" --password-stdin
            sudo docker build ./server -t karol22322/node-svr
            sudo docker push karol22322/node-svr
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "karol22322" --password-stdin
            sudo docker build ./client -t karol22322/cra-client
            sudo docker push karol22322/cra-client
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "karol22322" --password-stdin
            sudo docker build ./client -t karol22322/node-react-db
            sudo docker push karol22322/node-react-db
         
workflows:
    build-and-test:
      jobs:
        - build
        - node-server
        - react-client
        - docker-publish
