version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  node-server:
    executor:
      name: node/default
    steps:
      - run:
          command: npm test
          working_directory: ./server
  react-client:
      - checkout
      - node/install-packages:
          app-dir: ./client     
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - node-server
        - react-client
        command: npm test
        working_directory: ./server
react-client:
  executor:
    name: node/default
  steps:
    - checkout
    - node/install-packages:
      app-dir: ./client
