version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  node-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
  
  react-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client       
      - run:
          command: npm test
          working_directory: ./client
         
workflows:
    build-and-test:
      jobs:
        - node-server
        - react-client
